COINS SAMPLE SPACE

In [25]:
import numpy as np
import pandas as pd
def coin_sample_space(x):
  #x = int(ak)
  if x % 1 ==0:
    print("you have successfully entered a number between 1 and 3")
    a = ("coin")
    b=[]
    c=[]
    range_lst=[[] for i in range(2**x)]
    i=0
    if 1<= x <= 3:

      while i<x:
        div=2**(x-1-i)
        alt=0
        for j in range(2**x):
            if alt<div:    
                range_lst[j].append("H")
                alt+=1
            else:
                if alt==((div*2)-1):
                    alt-=((div*2)-1)
                else:
                    alt+=1
                range_lst[j].append("T")
        i+=1

      range_list = np.array(range_lst)
   #for i in range (len(a)):
      for i in range (1,x+1):
    #b= a+str[j]
        b.append(i)
      output = [str(i) for i in b]
  #print(output)
      for i in range(len(output)):
        d= a + output[i]
        c.append(d)
#print(b)
#print(c)
      df = pd.DataFrame(range_list, columns= c)
    else:
      print("enter a number between 1 to 3")
  else:
    print("you have entered a string please type between 1 and 3")
  return(df)

In [26]:
x = int(input("enter the number of coins:"))

coin_sample_space(x)

enter the number of coins:3
you have successfully entered a number between 1 and 3

  coin1 coin2 coin3
0     H     H     H
1     H     H     T
2     H     T     H
3     H     T     T
4     T     H     H
5     T     H     T
6     T     T     H
7     T     T     T

DICE SAMPLE SPACE

In [20]:
from itertools import product
def dice_sample_sapce(x):
  res = list(product(range(1, 7), repeat = x))
  a = ("dice")
  b=[]
  c=[]
  for i in range (1,x+1):
    #b= a+str[j]
        b.append(i)
  output = [str(i) for i in b]
  #print(output)
  for i in range(len(output)):
        d= a + output[i]
        c.append(d)
#print(b)
  print(c)
  df = pd.DataFrame(res, columns= c)
  return(df)

In [22]:
x = int(input("enter the number of coins:"))
dice_sample_sapce(x)

enter the number of coins:3
['dice1', 'dice2', 'dice3']

     dice1  dice2  dice3
0        1      1      1
1        1      1      2
2        1      1      3
3        1      1      4
4        1      1      5
..     ...    ...    ...
211      6      6      2
212      6      6      3
213      6      6      4
214      6      6      5
215      6      6      6

[216 rows x 3 columns]

In [32]:
import numpy as np
import pandas as pd
def coin_sample_space1(x):
  #x = int(ak)
  if x % 1 ==0:
    print("you have successfully entered a number between 1 and 3")
    a = ("coin")
    b=[]
    c=[]
    range_lst=[[] for i in range(2**x)]
    i=0
    if 1<= x <= 3:

      while i<x:
        div=2**(x-1-i)
        alt=0
        for j in range(2**x):
            if alt<div:    
                range_lst[j].append("H")
                alt+=1
            else:
                if alt==((div*2)-1):
                    alt-=((div*2)-1)
                else:
                    alt+=1
                range_lst[j].append("T")
        i+=1

      range_list = np.array(range_lst)
   #for i in range (len(a)):
      for i in range (1,x+1):
    #b= a+str[j]
        b.append(i)
      output = [str(i) for i in b]
  #print(output)
      for i in range(len(output)):
        d= a + output[i]
        c.append(d)
#print(b)
#print(c)
      df = pd.DataFrame(range_list, columns= c)
      sample_size = 2**x
      sample_size1 = 1/sample_size

      df['probs'] = float(sample_size1)
    else:
      print("enter a number between 1 to 3")
  else:
    print("you have entered a string please type between 1 and 3")
  return(df)

In [31]:
from itertools import product
def dice_sample_sapce1(x):
  res = list(product(range(1, 7), repeat = x))
  a = ("dice")
  b=[]
  c=[]
  for i in range (1,x+1):
    #b= a+str[j]
        b.append(i)
  output = [str(i) for i in b]
  #print(output)
  for i in range(len(output)):
        d= a + output[i]
        c.append(d)
#print(b)
  #print(c)
  df = pd.DataFrame(res, columns= c)
  sample_size = 6**x
  sample_size1 = 1/sample_size

  df['probs'] = float(sample_size1)
  return(df)

In [59]:
import pandas as pd
def probability(item):
  if item == "coin":
    x = int(input("enter the number of coins:"))
    coins = coin_sample_space1(x)
    #print(coins)
    df1 = pd.DataFrame(coins)
    return(df1)


  elif item == "dice":
    x = int(input("enter the number of dice:"))
    dices = dice_sample_sapce1(x)
    #print(dices)
    df1 = pd.DataFrame(dices)
    return(df1)
  else:
    print("type one of the following please 1.coin /n 2.dice")

In [71]:
item= input("enter your choice of item either coin or dice :")
probability(item)

enter your choice of item either coin or dice :dice
enter the number of dice:2
['dice1', 'dice2']

    dice1  dice2     probs
0       1      1  0.027778
1       1      2  0.027778
2       1      3  0.027778
3       1      4  0.027778
4       1      5  0.027778
5       1      6  0.027778
6       2      1  0.027778
7       2      2  0.027778
8       2      3  0.027778
9       2      4  0.027778
10      2      5  0.027778
11      2      6  0.027778
12      3      1  0.027778
13      3      2  0.027778
14      3      3  0.027778
15      3      4  0.027778
16      3      5  0.027778
17      3      6  0.027778
18      4      1  0.027778
19      4      2  0.027778
20      4      3  0.027778
21      4      4  0.027778
22      4      5  0.027778
23      4      6  0.027778
24      5      1  0.027778
25      5      2  0.027778
26      5      3  0.027778
27      5      4  0.027778
28      5      5  0.027778
29      5      6  0.027778
30      6      1  0.027778
31      6      2  0.027778
32      6      3  0.027778
33      6      4  0.027778
34      6      5  0.027778
35      6      6  0.027778

In [69]:
from IPython.core.interactiveshell import import_item
import_item